### PR TITLE
Fix ctr

### PR DESCRIPTION
**Pull request by deadcafe**

### CODE REVIEW

**Comment by tkanteck** [comment]
new file 'ctr_test.c' is missing a copyright/license header. Could you copy-paste proper header for the file here? I can add it in the process of merging. If you prefer to re-submit the whole patch then I am OK with it, too.
Thanks,
Tomasz

**Comment by deadcafe** [comment]
added copyright, and fixed a bit.

**Comment by deadcafe** [comment]
done, rebase master

**Comment by tkanteck** [comment]
thanks I'll look into it soon

**Comment by tkanteck** [comment]
Hi Deadcafe, the changes were just merged in f4ed204ccf1432e29bfff0938585748245f5be0a.
There is a few differences vs the original pull request:
(1) small assembly code restructure and use of memcpy macros for the partial block (no loads/stores beyond buffer)
(2) tests code restructure for clarity
(3) job valid check only changed to allow non-block sizes for CTR. The other changes allowed for more ways to use NULL_HASH and NULL_CIPHER modes which are not recommended
(4) Test code modified to compile & run on Windows
Thanks,
Tomasz

**Pull request closed without merging**
